apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-tim-resolver-tmdb
    kind: ClusterSecretStore
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "name:sentry-dsn"
        decodingStrategy: None
  dataFrom:
    - extract:
        key: "name:manual-secrets"
        decodingStrategy: None
